# Generated by Django 2.2.3 on 2019-07-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190716_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date', '-modified_date'], 'verbose_name': 'BlogPost'},
        ),
    ]
